# Generated by Django 3.2.8 on 2023-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
