# Generated by Django 3.2.8 on 2023-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
