# Generated by Django 3.2.8 on 2023-04-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20230420_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
    ]
