# Generated by Django 3.2.8 on 2023-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20230425_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bo_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='bo_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='bo_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lose',
            field=models.IntegerField(default=0),
        ),
    ]
