# Generated by Django 3.2.8 on 2023-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20230427_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
