# Generated by Django 3.2.8 on 2023-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20230514_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='split',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='split',
            field=models.IntegerField(default=1),
        ),
    ]
