# Generated by Django 3.2.8 on 2023-06-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
